# Public constants for API enums

INCOME_TYPE_INDIVIDUAL = "FROM_INDIVIDUAL"
INCOME_TYPE_LEGAL_ENTITY = "FROM_LEGAL_ENTITY"
INCOME_TYPE_FOREIGN_AGENCY = "FROM_FOREIGN_AGENCY"

PAYMENT_TYPE_CASH = "CASH"
PAYMENT_TYPE_ACCOUNT = "ACCOUNT"

CANCEL_COMMENT_CANCEL = "Чек сформирован ошибочно"
CANCEL_COMMENT_REFUND = "Возврат средств"

DEFAULT_BASE_URL = "https://lknpd.nalog.ru/api/v1"

